 Tensor flow, fundemental concepts of tensors
* Introduction to tensors, getting information, manipulating tensors, Tensor &Numpy
* Using Gpus with tensorflow or TPU
* Using @tf.function( a way to speed up regular python function)

In [1]:
#  Import tensorflow
import tensorflow as tf
print(tf.__version__)

2.15.0


In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
#creating tensors with tf.constant(), tensor has many built in models such as this to read in the data source
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# check the number of dimension of tensor(ndim)
scalar.ndim


0

In [5]:
# create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
vector.ndim

1

In [7]:
#create a matrix(has more than 1 dimension)
matrix = tf.constant([[10,7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [8]:
matrix.ndim

2

In [9]:
#create a nother matrix
matrix1 = tf.constant([[10.,7.],
                      [7., 10.],
                       [2.,3.]], dtype = tf.float16) #dtype to manuplate the data type
matrix1

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.],
       [ 2.,  3.]], dtype=float16)>

In [10]:
matrix.ndim

2

In [11]:
#lets a create a tensor
tensor = tf.constant([[[1,2,3,],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [12]:
tensor.ndim

3

* scalar is single number
* Vector a number with direction (eg wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: a n-dimensional ( 0 to n), array of numbers , 0 is scalar, 1 is vector


In [13]:
# create with tf.Variable

In [14]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [15]:
changaeble_tensor = tf.Variable([10,7])
unchangaeble_tensor = tf.constant([10,7])
changaeble_tensor, unchangaeble_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [16]:
changaeble_tensor[0].assign(7) #.assign to change values

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [17]:
changaeble_tensor #.assign doesnt work for other unchan...

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

Random Tensors

In [18]:
#rarely in practice you need to decide if you need to go with tf.constant or tf.Variable. However, in doubt use tf.constant and change it later if needed

In [19]:
#random tensors are of random size fileed with arbitary numbers

In [20]:
#create two random tensors(but the same)

In [21]:
random1= tf.random.Generator.from_seed(42) #set seed for repdoucibility

In [22]:
random1 = random1.normal(shape=(3,2))

In [23]:
random1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [24]:
random2= tf.random.Generator.from_seed(42)
random2 = random2.normal(shape=(3,2))
random1, random2, random1==random2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

Shuffle order of elements in Tensor
* in food image class ang 15k images categories, first 2k of apple, next of banana, and so on... It will be good idea to mix up the images and neural network will learn them at same time
* inherent order doesnt affect learning

In [25]:
not_shuffles = tf.constant([[10,7],
                           [3,4],
                            [3,3]])
not_shuffles.ndim

2

In [26]:
# to shuffle
# tf.random.shuffle(value, seed = None, name = None) RANDOMLY SHUFFLES IN FIRST DIMENSION, value is tensor to be shuffled, seed is python integer, Name of the operation(optional)

In [27]:
tf.random.shuffle(not_shuffles)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  3],
       [ 3,  4]], dtype=int32)>

In [28]:
#It lloks like if we want to shuffle tensors to be in the same order, we have to use the global level as weel as operational level random seed

In [29]:
tf.random.set_seed(42) # global level random seed
tf.random.shuffle(not_shuffles, seed =42) #operational levelr andom seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 3,  3]], dtype=int32)>

In [30]:
### others ways to make tensors

In [31]:
tf.ones([3,4], dtype=float)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [32]:
tf.zeros([2,3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [33]:
#you can also turn numpy arrays into tensors, the main difference betweeen both is tensors can be run on gpu than numerical computing

In [34]:
import numpy as np
numpy_A = np.arange(1, 25, dtype = np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [35]:
A =tf.constant(numpy_A, shape =(2,3,4)) #shape not mandatory just to show 2*3*4=24
A #since it is in a tensor format it run faster on a gpu processor

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

Getting information from tensors:
* shape -> the length(no of elements) in each dimension of a tensor, tensor.shape
* rank -> T number of tensor dimension, scalar 0 , vector 1, matrix 2, tensor n. tensor.ndim
* axis or dimension -> a particular dimension of tensor, tensor[0],...tensor[:,1]
* size-> total number of elements in tensor, ts.size(tensor)

In [36]:
#create 4 dimension tensors
rank_4_tensor = tf.zeros([2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [37]:
#when we pass a tensor to neural network it should be of particular shape, even when it comes out

In [38]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [39]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [40]:
#get various attributes of our tensor
print("Data type of every elemrnt:", rank_4_tensor.dtype)
print("Number of dimensions: ", rank_4_tensor.ndim)
print("shape of tensor: ", rank_4_tensor.shape)
print("elements along 0 axis ", rank_4_tensor.shape[0])
print("elements along last axis ", rank_4_tensor.shape[-1])
print("total number of elements ", tf.size(rank_4_tensor).numpy())

Data type of every elemrnt: <dtype: 'float32'>
Number of dimensions:  4
shape of tensor:  (2, 3, 4, 5)
elements along 0 axis  2
elements along last axis  5
total number of elements  120


Indexing tensors:
Tensors can be indexed like python list

In [41]:
# getting first two element of each tensor
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [42]:
#get the first element from each dimension from each index except the final one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [43]:
# expanding tensor
rank2 = tf.constant([[10,7],
                     [3,4]])
rank2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [44]:
#last element in each row of rank2 tensor
rank2[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [45]:
#add extra information
rank3 = rank2[... , tf.newaxis] # ...-> every axis before new one
rank3

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [46]:
rank3 = rank2[:, tf.newaxis, :]
rank3

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]], dtype=int32)>

In [47]:
tf.expand_dims(rank2, axis=-1) #alternate, (input = tensor, axis = integer, name=)


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

Matrix multiplication

In [48]:
matrix = tf.constant([[10,7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [49]:
matrix+=10
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [17, 20]], dtype=int32)>

Need to '.' product, the usual multiplication

In [50]:
tf.matmul(matrix,matrix)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[689, 680],
       [680, 689]], dtype=int32)>

In [51]:
matrix * matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[400, 289],
       [289, 400]], dtype=int32)>

See the difference

In [52]:
tensor = tf.constant([[10,7],
                      [7, 10],
                       [7, 10]])
tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10],
       [ 7, 10]], dtype=int32)>

In [53]:
tensor @ tensor, tf.matmul(matrix,matrix)=> basic rules apply

SyntaxError: ignored

In [54]:
tf.transpose(tensor)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10,  7,  7],
       [ 7, 10, 10]], dtype=int32)>

**The Dot Product**

Matrix multiplication is also called dot product.

tf.matmul()

tf.tensordot()

In [55]:
tf.tensordot(tf.transpose(tensor),tensor,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[198, 210],
       [210, 249]], dtype=int32)>

Changing datatype, default int32

In [57]:
tensor = tf.constant([[10,7],
                      [7, 10],
                       [7, 10]])
tensor1 = tf.cast(tensor , tf.float32)
tensor1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[10.,  7.],
       [ 7., 10.],
       [ 7., 10.]], dtype=float32)>

In [58]:
tensor = tf.constant([[-10,-7],
                      [-7, -10],
                       [-7, -10]])
tf.abs(tensor)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10],
       [ 7, 10]], dtype=int32)>

more aggregration

In [63]:
tensor = tf.constant(np.random.randint(0,100,size=50))
tensor

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([68, 19, 11, 94, 60, 31, 79, 96, 42, 61, 86, 47, 96, 84, 37, 52, 98,
       92, 76, 43, 70, 63, 48, 23,  4, 77,  1, 68, 73, 88, 11, 15, 85, 10,
       80, 88, 92, 80, 48, 19, 59, 47, 85, 14, 18, 86, 54, 94, 60, 65])>

In [64]:
tf.size(tensor), tensor.shape, tensor.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [65]:
tf.reduce_min(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [66]:
tf.reduce_max(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [67]:
tf.reduce_mean(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=57>

In [68]:
tf.reduce_sum(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=2897>

In [69]:
import tensorflow_probability as tfp  #need to import to fnd variance
tfp.stats.variance(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=847>

In [71]:
tf.math.reduce_std(tf.cast(tensor, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=29.097359>

In [72]:
tf.math.reduce_variance(tf.cast(tensor, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=846.6563>

Finding the positional maximum and minimum

In [73]:
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [78]:
F[tf.argmax(F)].numpy()

0.9671384

In [79]:
tf.reduce_max(F).numpy()

0.9671384

In [81]:
 F[tf.argmax(F)].numpy() == tf.reduce_max(F).numpy()

True

Squeezing tensor

In [83]:
tf.random.set_seed(42)
F = tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
F

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [85]:
F.shape

TensorShape([1, 1, 1, 1, 50])

In [87]:
g_squeeze = tf.squeeze(F) #removes 1 dimension
g_squeeze.shape

TensorShape([50])

In [88]:
some_list = [0,1,2,3]

tf.one_hot(some_list, depth =4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [89]:
tf.one_hot(some_list, depth =4, on_value="ooo", off_value="l")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'ooo', b'l', b'l', b'l'],
       [b'l', b'ooo', b'l', b'l'],
       [b'l', b'l', b'ooo', b'l'],
       [b'l', b'l', b'l', b'ooo']], dtype=object)>

In [90]:
tf.square(F)

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[4.4164279e-01, 1.9448698e-01, 1.2452606e-01, 2.1574403e-01,
           1.1330233e-03, 4.6877623e-01, 5.4777384e-01, 7.6115942e-01,
           5.1223613e-02, 4.9816839e-02, 9.6340768e-02, 5.2176905e-01,
           1.7738823e-02, 3.0037400e-01, 3.3017528e-01, 8.0943036e-01,
           8.9561006e-05, 2.7168143e-01, 4.0264672e-01, 3.9731771e-02,
           5.3205711e-01, 2.9793534e-01, 1.1570342e-02, 4.5793110e-01,
           4.3596479e-01, 1.1353558e-01, 3.6170322e-01, 4.4363216e-02,
           7.2716069e-01, 1.9414751e-01, 8.9970458e-01, 5.6418572e-02,
           6.5900785e-01, 2.7703318e-01, 2.4434039e-01, 4.6711516e-02,
           7.1524179e-01, 7.6018190e-01, 9.5102049e-02, 4.7169948e-01,
           5.6472950e-02, 6.1109054e-01, 9.3535668e-01, 4.7199135e-03,
           6.3798469e-01, 4.3597910e-01, 3.4474665e-01, 2.7098738e-02,
           5.4479504e-01, 1.0274617e-01]]]]], dtype=float32)>

In [92]:
#find the square root, requires non int type

tf.sqrt(tf.cast(F,dtype=tf.float32))

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.81520677, 0.6640834 , 0.59403914, 0.6815296 , 0.18346775,
           0.8274493 , 0.8603008 , 0.9340474 , 0.4757377 , 0.47243714,
           0.55712485, 0.8499034 , 0.36494818, 0.74031335, 0.7580296 ,
           0.9485165 , 0.09728138, 0.7219631 , 0.796583  , 0.44646198,
           0.8540623 , 0.7388062 , 0.32797185, 0.82262146, 0.81257385,
           0.5804743 , 0.7755112 , 0.45893982, 0.9234377 , 0.66379344,
           0.9739238 , 0.48736632, 0.90099555, 0.72549254, 0.7030704 ,
           0.4648962 , 0.91963017, 0.93374735, 0.5553253 , 0.8287363 ,
           0.4874837 , 0.88415086, 0.98343194, 0.26210994, 0.89372224,
           0.8125805 , 0.766258  , 0.40573013, 0.85912883, 0.5661629 ]]]]],
      dtype=float32)>

In [93]:
#same as before
tf.math.log(tf.cast(F,dtype=tf.float32))

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[-0.40862694, -0.818695  , -1.0416201 , -0.7668313 ,
           -3.3914328 , -0.37881485, -0.3009464 , -0.13645622,
           -1.4857774 , -1.4997011 , -1.1699319 , -0.32526514,
           -2.0159998 , -0.6013634 , -0.5540658 , -0.10571226,
           -4.6602955 , -0.6515625 , -0.45484787, -1.612802  ,
           -0.31550223, -0.60543936, -2.229655  , -0.39051828,
           -0.4150969 , -1.0878195 , -0.50846565, -1.5576724 ,
           -0.15930387, -0.8195685 , -0.05284442, -1.4374784 ,
           -0.20850994, -0.641809  , -0.70459646, -1.5318823 ,
           -0.16756731, -0.13709876, -1.1764023 , -0.37570658,
           -1.4369967 , -0.2462551 , -0.03341366, -2.6779823 ,
           -0.22472048, -0.41508046, -0.5324727 , -1.8041341 ,
           -0.30367282, -1.1377468 ]]]]], dtype=float32)>

tensor flow and numpy arrays

In [94]:
J = tf.constant(np.array([1,2,3,4,5]))
J

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([1, 2, 3, 4, 5])>

In [97]:
#convert back to np
np.array(J), J.numpy()

(array([1, 2, 3, 4, 5]), array([1, 2, 3, 4, 5]))